/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * dgl_AddPoint.java
 *
 * Created on Mar 12, 2012, 2:14:50 AM
 */
package travelsmart;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.awt.event.MouseEvent;
import javax.swing.SwingUtilities;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 *
 * @author dato
 */
public class dgl_AddPoint extends javax.swing.JDialog {
    objPoint tempPoint;
    int mouseX;
    int mouseY;
    
    /** Creates new form dgl_AddPoint */
    public dgl_AddPoint() {
        initComponents();
        this.lblIndex.setText(String.valueOf(FileProcess.getNewPointIndex(TravelSmart.getApplication().pointCollect)));
        this.txtPosX.setText("0");
        this.txtPosY.setText("0");
        this.setBackground(new Color(0,0,0,0));
        this.getContentPane().setBackground(new Color(0,0,0,0));
        this.bgPanel.bgUrl = Config.myDialog_bg;
        
        // Listen for changes in the text
        this.txtName.getDocument().addDocumentListener(new DocumentListener() {
            public void changedUpdate(DocumentEvent e) {
                warn();
            }
            public void removeUpdate(DocumentEvent e) {
                warn();
            }
            public void insertUpdate(DocumentEvent e) {
                warn();
            }

            public void warn() {
                String Name;
                if(txtName.getText().equals("")){
                    Name = " ";
                }else Name = txtName.getText();
                tempPoint.Name = Name;
                tempPoint.SetPointState(0);
            }
        });
        
        this.txtPosX.getDocument().addDocumentListener(new DocumentListener() {
            public void changedUpdate(DocumentEvent e) {
                warn();
            }
            public void removeUpdate(DocumentEvent e) {
                warn();
            }
            public void insertUpdate(DocumentEvent e) {
                warn();
            }

            public void warn() {
                int x;
                if(txtPosX.getText().equals("")) x=0;
                else x = Integer.parseInt(txtPosX.getText());
                if(x>=0 || x<=1600){
                    tempPoint.setPosX(x);
                    tempPoint.SetPointState(0);
                }else{
                    SwingUtilities.invokeLater(new Runnable() {

                        public void run() {
                            txtPosX.setText(String.valueOf(tempPoint.getPosX()));
                        }
                    });
                }
            }
        });
        
        this.txtPosY.getDocument().addDocumentListener(new DocumentListener() {
            public void changedUpdate(DocumentEvent e) {
                warn();
            }
            public void removeUpdate(DocumentEvent e) {
                warn();
            }
            public void insertUpdate(DocumentEvent e) {
                warn();
            }

            public void warn() {
                int y;
                if(txtPosY.getText().equals("")) y=0;
                else y = Integer.parseInt(txtPosY.getText());
                if(y>=0||y<=900){
                    tempPoint.setPosY(y);
                    tempPoint.SetPointState(0);                    
                }else{
                    SwingUtilities.invokeLater(new Runnable() {

                        public void run() {
                            txtPosX.setText(String.valueOf(tempPoint.getPosY()));
                        }
                    });
                }
            }
        });
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        bgPanel = new travelsmart.bgPanel();
        jButton1 = new javax.swing.JButton();
        Container = new travelsmart.bgPanel();
        lblIndex = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        bttSave = new javax.swing.JButton();
        txtPosX = new javax.swing.JTextField();
        txtPosY = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        bttCancel = new javax.swing.JButton();

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(travelsmart.TravelSmart.class).getContext().getResourceMap(dgl_AddPoint.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setAlwaysOnTop(true);
        setName("Form"); // NOI18N
        setUndecorated(true);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                formComponentHidden(evt);
            }
        });
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        getContentPane().setLayout(new java.awt.GridBagLayout());

        bgPanel.setMaximumSize(new java.awt.Dimension(216, 142));
        bgPanel.setMinimumSize(new java.awt.Dimension(216, 142));
        bgPanel.setName("bgPanel"); // NOI18N
        bgPanel.setLayout(new java.awt.GridBagLayout());

        jButton1.setIcon(resourceMap.getIcon("jButton1.icon")); // NOI18N
        jButton1.setBorder(null);
        jButton1.setContentAreaFilled(false);
        jButton1.setFocusPainted(false);
        jButton1.setName("jButton1"); // NOI18N
        jButton1.setRolloverIcon(resourceMap.getIcon("jButton1.rolloverIcon")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 10);
        bgPanel.add(jButton1, gridBagConstraints);

        Container.setMaximumSize(new java.awt.Dimension(219, 77));
        Container.setMinimumSize(new java.awt.Dimension(219, 77));
        Container.setName("Container"); // NOI18N
        Container.setPreferredSize(new java.awt.Dimension(219, 77));

        lblIndex.setForeground(resourceMap.getColor("lblIndex.foreground")); // NOI18N
        lblIndex.setText(resourceMap.getString("lblIndex.text")); // NOI18N
        lblIndex.setName("lblIndex"); // NOI18N

        txtName.setBackground(resourceMap.getColor("txtName.background")); // NOI18N
        txtName.setText(resourceMap.getString("txtName.text")); // NOI18N
        txtName.setName("txtName"); // NOI18N
        txtName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNameFocusLost(evt);
            }
        });
        txtName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNameKeyPressed(evt);
            }
        });

        jLabel3.setForeground(resourceMap.getColor("jLabel3.foreground")); // NOI18N
        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        jLabel4.setForeground(resourceMap.getColor("jLabel4.foreground")); // NOI18N
        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N

        bttSave.setIcon(resourceMap.getIcon("bttSave.icon")); // NOI18N
        bttSave.setText(resourceMap.getString("bttSave.text")); // NOI18N
        bttSave.setBorder(null);
        bttSave.setContentAreaFilled(false);
        bttSave.setFocusPainted(false);
        bttSave.setName("bttSave"); // NOI18N
        bttSave.setPressedIcon(resourceMap.getIcon("bttSave.pressedIcon")); // NOI18N
        bttSave.setRolloverIcon(resourceMap.getIcon("bttSave.rolloverIcon")); // NOI18N
        bttSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttSaveActionPerformed(evt);
            }
        });

        txtPosX.setBackground(resourceMap.getColor("txtPosX.background")); // NOI18N
        txtPosX.setName("txtPosX"); // NOI18N
        txtPosX.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNameKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPosXKeyTyped(evt);
            }
        });

        txtPosY.setBackground(resourceMap.getColor("txtPosY.background")); // NOI18N
        txtPosY.setText(resourceMap.getString("txtPosY.text")); // NOI18N
        txtPosY.setMinimumSize(new java.awt.Dimension(30, 20));
        txtPosY.setName("txtPosY"); // NOI18N
        txtPosY.setPreferredSize(new java.awt.Dimension(30, 20));
        txtPosY.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNameKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPosYKeyTyped(evt);
            }
        });

        jLabel1.setForeground(resourceMap.getColor("jLabel1.foreground")); // NOI18N
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        bttCancel.setIcon(resourceMap.getIcon("bttCancel.icon")); // NOI18N
        bttCancel.setText(resourceMap.getString("bttCancel.text")); // NOI18N
        bttCancel.setBorder(null);
        bttCancel.setContentAreaFilled(false);
        bttCancel.setFocusPainted(false);
        bttCancel.setName("bttCancel"); // NOI18N
        bttCancel.setPressedIcon(resourceMap.getIcon("bttCancel.pressedIcon")); // NOI18N
        bttCancel.setRolloverIcon(resourceMap.getIcon("bttCancel.rolloverIcon")); // NOI18N
        bttCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ContainerLayout = new javax.swing.GroupLayout(Container);
        Container.setLayout(ContainerLayout);
        ContainerLayout.setHorizontalGroup(
            ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContainerLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblIndex))
            .addGroup(ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addGroup(ContainerLayout.createSequentialGroup()
                    .addComponent(bttSave)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(bttCancel))
                .addGroup(ContainerLayout.createSequentialGroup()
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jLabel3)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(txtPosX, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel4)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(txtPosY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        ContainerLayout.setVerticalGroup(
            ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContainerLayout.createSequentialGroup()
                .addGroup(ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblIndex))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPosX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(txtPosY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bttSave)
                    .addComponent(bttCancel))
                .addContainerGap())
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 10);
        bgPanel.add(Container, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(bgPanel, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void txtNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNameFocusLost
// TODO add your handling code here:
    if(this.txtName.getText().equals("")){
        this.txtName.setText("Type name in here");
    }    
}//GEN-LAST:event_txtNameFocusLost

private void bttSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttSaveActionPerformed
// TODO add your handling code here:
    objPoint newPoint = new objPoint(this.txtName.getText(),Integer.parseInt(this.txtPosX.getText()),Integer.parseInt(this.txtPosY.getText()),Integer.parseInt(this.lblIndex.getText()));
    newPoint.ChangeStatus(MapStatus.EDIT_POINT);
    FileProcess.addPoint(newPoint);
    //Add point to map
    TravelSmart.getApplication().pointCollect.add(newPoint);
    TravelSmart.getView().pn_Map.add(newPoint);
    TravelSmart.getView().pn_Map.repaint();
    //Reset form
    this.lblIndex.setText(String.valueOf(FileProcess.getNewPointIndex(TravelSmart.getApplication().pointCollect)));
    this.txtName.setText("");
    this.UpdatePos(0, 0);
    //Close this dialog
    this.setVisible(false);
}//GEN-LAST:event_bttSaveActionPerformed

private void bttCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttCancelActionPerformed
    TravelSmart.getView().pn_Map.remove(tempPoint);
    TravelSmart.getView().pn_Map.repaint();
    this.setVisible(false);
}//GEN-LAST:event_bttCancelActionPerformed

private void formComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentHidden
    bttCancelActionPerformed(null);
}//GEN-LAST:event_formComponentHidden

private void txtNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNameFocusGained
    if(this.txtName.getText().equals("Type name in here")){
        this.txtName.setText("");
    }   
}//GEN-LAST:event_txtNameFocusGained

private void txtNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNameKeyPressed
    if(evt.getKeyCode() == KeyEvent.VK_ENTER){
        bttSaveActionPerformed(null);
    }else if (evt.getKeyCode() == KeyEvent.VK_ESCAPE){
        bttCancelActionPerformed(null);
    }
}//GEN-LAST:event_txtNameKeyPressed

private void txtPosXKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPosXKeyTyped
    String badchars = "`~!@#$%^&*()_+=\\|\"':;?/>.<, -";
    char c = evt.getKeyChar();
    if((Character.isLetter(c) && !evt.isAltDown()) || badchars.indexOf(c) > -1) {
        evt.consume();
        return;
    }
    if(c == '-' && txtPosX.getDocument().getLength() > 0) evt.consume();
    else super.processKeyEvent(evt);
}//GEN-LAST:event_txtPosXKeyTyped

private void txtPosYKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPosYKeyTyped
    String badchars = "`~!@#$%^&*()_+=\\|\"':;?/>.<, -";
    char c = evt.getKeyChar();
    if((Character.isLetter(c) && !evt.isAltDown()) || badchars.indexOf(c) > -1) {
        evt.consume();
        return;
    }
    if(c == '-' && txtPosY.getDocument().getLength() > 0) evt.consume();
    else super.processKeyEvent(evt);
}//GEN-LAST:event_txtPosYKeyTyped

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    bttCancelActionPerformed(evt);
}//GEN-LAST:event_jButton1ActionPerformed

private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
    this.setLocation(this.getLocation().x- mouseX + evt.getX(), this.getLocation().y- mouseY +evt.getY());
}//GEN-LAST:event_formMouseDragged

private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
    this.mouseX = evt.getX();
    this.mouseY = evt.getY();
}//GEN-LAST:event_formMousePressed

    public void showDgl(MouseEvent e){
        this.setLocation(e.getXOnScreen(), e.getYOnScreen());
        if(!this.isVisible()) this.setVisible(true);
        else{
            this.setAlwaysOnTop(true);
        }
        //Add template point to map
        if(tempPoint != null){
            TravelSmart.getView().pn_Map.remove(tempPoint);
            TravelSmart.getView().pn_Map.repaint();
        }
        tempPoint = new objPoint("Type name in here", e.getX(), e.getY(), FileProcess.getNewPointIndex(TravelSmart.getApplication().pointCollect));
        tempPoint.ChangeStatus(MapStatus.VIEW);
        this.lblIndex.setText(String.valueOf(FileProcess.getNewPointIndex(TravelSmart.getApplication().pointCollect)));
        TravelSmart.getView().pn_Map.add(tempPoint);
        tempPoint.SetPointState(0);
        
        UpdatePos(e.getX(), e.getY());
    }
    
    public void UpdatePos(int xonMap,int yonMap){
        int x = (int)(Double.valueOf(xonMap - Config.Map_Margin_LR)/Double.valueOf(TravelSmart.getView().pn_Map.getWidth()-2*Config.Map_Margin_LR)*1600);
        int y = (int)(Double.valueOf(yonMap - Config.Map_Margin_TB)/Double.valueOf(TravelSmart.getView().pn_Map.getHeight()-2*Config.Map_Margin_TB)*900);
        this.txtPosX.setText(String.valueOf(x));
        this.txtPosY.setText(String.valueOf(y));
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private travelsmart.bgPanel Container;
    private travelsmart.bgPanel bgPanel;
    private javax.swing.JButton bttCancel;
    private javax.swing.JButton bttSave;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblIndex;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPosX;
    private javax.swing.JTextField txtPosY;
    // End of variables declaration//GEN-END:variables
}
