/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * dgl_AddPoint.java
 *
 * Created on Mar 12, 2012, 2:14:50 AM
 */
package travelsmart;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.event.KeyEvent;
import javax.swing.ImageIcon;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 *
 * @author dato
 */
public class dgl_AddLine extends javax.swing.JDialog {
    objLine tempLine;
    int mouseX,mouseY;
    
    /** Creates new form dgl_AddPoint */
    public dgl_AddLine() {
        initComponents();
        this.lblIndex.setText(String.valueOf(FileProcess.getNewLineIndex(TravelSmart.getApplication().lineCollect)));
        //Set background for dialog
        this.setBackground(new Color(0,0,0,0));
        this.getContentPane().setBackground(new Color(0,0,0,50));
        this.bgPanel.bgUrl = Config.myDialog_bg;
        
        // Listen for changes in the text
        this.txtLength.getDocument().addDocumentListener(new DocumentListener() {
            public void changedUpdate(DocumentEvent e) {
                warn();
            }
            public void removeUpdate(DocumentEvent e) {
                warn();
            }
            public void insertUpdate(DocumentEvent e) {
                warn();
            }

            public void warn() {
                Double length;
                if(txtLength.getText().equals("")){
                    length = 0.0;
                }else {
                    try{                    
                        length = Double.valueOf(txtLength.getText());
                        tempLine.Length = length;
                        tempLine.SetLineState(2);
                    }catch(NumberFormatException e){
                        //txtLength.setText("0");
                    }
                }
            }
        });
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        bgPanel = new travelsmart.bgPanel();
        Container = new travelsmart.bgPanel();
        lblIndex = new javax.swing.JLabel();
        txtLength = new javax.swing.JTextField();
        bttAdd = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        bttCancel = new javax.swing.JButton();
        bttClose = new javax.swing.JButton();

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(travelsmart.TravelSmart.class).getContext().getResourceMap(dgl_AddLine.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setAlwaysOnTop(true);
        setBackground(resourceMap.getColor("Form.background")); // NOI18N
        setName("Form"); // NOI18N
        setResizable(false);
        setUndecorated(true);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                formComponentHidden(evt);
            }
        });
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        getContentPane().setLayout(new java.awt.GridBagLayout());

        bgPanel.setMaximumSize(new java.awt.Dimension(216, 142));
        bgPanel.setMinimumSize(new java.awt.Dimension(216, 142));
        bgPanel.setName("bgPanel"); // NOI18N
        bgPanel.setLayout(new java.awt.GridBagLayout());

        Container.setMaximumSize(new java.awt.Dimension(208, 82));
        Container.setMinimumSize(new java.awt.Dimension(208, 82));
        Container.setName("Container"); // NOI18N

        lblIndex.setForeground(resourceMap.getColor("lblIndex.foreground")); // NOI18N
        lblIndex.setText(resourceMap.getString("lblIndex.text")); // NOI18N
        lblIndex.setName("lblIndex"); // NOI18N

        txtLength.setBackground(resourceMap.getColor("txtLength.background")); // NOI18N
        txtLength.setText(resourceMap.getString("txtLength.text")); // NOI18N
        txtLength.setName("txtLength"); // NOI18N
        txtLength.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtLengthFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtLengthFocusLost(evt);
            }
        });
        txtLength.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtLengthKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtLengthKeyTyped(evt);
            }
        });

        bttAdd.setIcon(resourceMap.getIcon("bttAdd.icon")); // NOI18N
        bttAdd.setText(resourceMap.getString("bttAdd.text")); // NOI18N
        bttAdd.setBorder(null);
        bttAdd.setContentAreaFilled(false);
        bttAdd.setFocusPainted(false);
        bttAdd.setMargin(new java.awt.Insets(0, 0, 0, 0));
        bttAdd.setName("bttAdd"); // NOI18N
        bttAdd.setPressedIcon(resourceMap.getIcon("bttAdd.pressedIcon")); // NOI18N
        bttAdd.setRolloverIcon(resourceMap.getIcon("bttAdd.rolloverIcon")); // NOI18N
        bttAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttAddActionPerformed(evt);
            }
        });

        jLabel1.setForeground(resourceMap.getColor("jLabel1.foreground")); // NOI18N
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        bttCancel.setIcon(resourceMap.getIcon("bttCancel.icon")); // NOI18N
        bttCancel.setText(resourceMap.getString("bttCancel.text")); // NOI18N
        bttCancel.setBorder(null);
        bttCancel.setContentAreaFilled(false);
        bttCancel.setFocusPainted(false);
        bttCancel.setName("bttCancel"); // NOI18N
        bttCancel.setPressedIcon(resourceMap.getIcon("bttCancel.pressedIcon")); // NOI18N
        bttCancel.setRolloverIcon(resourceMap.getIcon("bttCancel.rolloverIcon")); // NOI18N
        bttCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ContainerLayout = new javax.swing.GroupLayout(Container);
        Container.setLayout(ContainerLayout);
        ContainerLayout.setHorizontalGroup(
            ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContainerLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(6, 6, 6)
                .addComponent(lblIndex))
            .addGroup(ContainerLayout.createSequentialGroup()
                .addComponent(bttAdd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(bttCancel))
            .addComponent(txtLength, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
        );
        ContainerLayout.setVerticalGroup(
            ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContainerLayout.createSequentialGroup()
                .addGroup(ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(lblIndex))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtLength, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bttCancel)
                    .addComponent(bttAdd)))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        bgPanel.add(Container, gridBagConstraints);

        bttClose.setIcon(resourceMap.getIcon("bttClose.icon")); // NOI18N
        bttClose.setText(resourceMap.getString("bttClose.text")); // NOI18N
        bttClose.setBorder(null);
        bttClose.setContentAreaFilled(false);
        bttClose.setFocusPainted(false);
        bttClose.setName("bttClose"); // NOI18N
        bttClose.setRolloverIcon(resourceMap.getIcon("bttClose.rolloverIcon")); // NOI18N
        bttClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttCloseActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 10);
        bgPanel.add(bttClose, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(bgPanel, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void txtLengthFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtLengthFocusLost
// TODO add your handling code here:
    if(this.txtLength.getText().equals("")){
        this.txtLength.setText("0");
    }    
}//GEN-LAST:event_txtLengthFocusLost

private void bttAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttAddActionPerformed
    objLine newLine = new objLine(Integer.parseInt(this.lblIndex.getText()),tempLine.Start,tempLine.End,Double.valueOf(this.txtLength.getText()));
    newLine.ChangeStatus(MapStatus.EDIT_LINE);
    FileProcess.addLine(newLine);
    //Add point to map
    TravelSmart.getApplication().lineCollect.add(newLine);
    TravelSmart.getView().pn_Map.add(newLine);
    TravelSmart.getView().pn_Map.remove(tempLine);
    TravelSmart.getView().pn_Map.repaint();
    //Reset form
    this.lblIndex.setText(String.valueOf(FileProcess.getNewLineIndex(TravelSmart.getApplication().lineCollect)));
    this.txtLength.setText("0");
    //Close this dialog
    this.setVisible(false);
}//GEN-LAST:event_bttAddActionPerformed

private void bttCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttCancelActionPerformed
    TravelSmart.getView().pn_Map.remove(tempLine);
    TravelSmart.getView().pn_Map.repaint();
    this.setVisible(false);
}//GEN-LAST:event_bttCancelActionPerformed

private void formComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentHidden
    bttCancelActionPerformed(null);
}//GEN-LAST:event_formComponentHidden

private void txtLengthFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtLengthFocusGained
    if(this.txtLength.getText().equals("Type length in here")){
        this.txtLength.setText("0");
    }   
}//GEN-LAST:event_txtLengthFocusGained

private void txtLengthKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLengthKeyPressed

    if(evt.getKeyCode() == KeyEvent.VK_ENTER){
        bttAddActionPerformed(null);
    }else if (evt.getKeyCode() == KeyEvent.VK_ESCAPE){
        bttCancelActionPerformed(null);
    }    
}//GEN-LAST:event_txtLengthKeyPressed

private void txtLengthKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLengthKeyTyped
    String badchars = "`~!@#$%^&*()_+=\\|\"':;?/><, -";
    char c = evt.getKeyChar();
    if((Character.isLetter(c) && !evt.isAltDown()) || badchars.indexOf(c) > -1) {
        evt.consume();
        return;
    }
    if(c == '-' && txtLength.getDocument().getLength() > 0) evt.consume();
    else super.processKeyEvent(evt);
}//GEN-LAST:event_txtLengthKeyTyped

private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
    this.setLocation(this.getLocation().x- mouseX + evt.getX(), this.getLocation().y- mouseY +evt.getY());
}//GEN-LAST:event_formMouseDragged

private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
    this.mouseX = evt.getX();
    this.mouseY = evt.getY();
}//GEN-LAST:event_formMousePressed

private void bttCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttCloseActionPerformed
    bttCancelActionPerformed(evt);
}//GEN-LAST:event_bttCloseActionPerformed

    public void showDgl(objPoint Start, objPoint End){
        this.setLocation((Start.getLocationOnScreen().x+Start.getWidth()/2+End.getLocationOnScreen().x+End.getWidth()/2)/2, (Start.getLocationOnScreen().y+Start.getHeight()+End.getLocationOnScreen().y+End.getHeight())/2);
        if(!this.isVisible()) this.setVisible(true);
        //Add template point to map
        if(tempLine != null){
            TravelSmart.getView().pn_Map.remove(tempLine);
            TravelSmart.getView().pn_Map.repaint();
        }
        tempLine = new objLine(FileProcess.getNewLineIndex(TravelSmart.getApplication().lineCollect),Start,End,0);
        tempLine.ChangeStatus(MapStatus.EDIT_LINE);
        TravelSmart.getView().pn_Map.add(tempLine);
        tempLine.SetLineState(2);
        this.lblIndex.setText(String.valueOf(tempLine.Index));
        this.txtLength.setText(String.valueOf(tempLine.Length));
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private travelsmart.bgPanel Container;
    private travelsmart.bgPanel bgPanel;
    private javax.swing.JButton bttAdd;
    private javax.swing.JButton bttCancel;
    private javax.swing.JButton bttClose;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblIndex;
    private javax.swing.JTextField txtLength;
    // End of variables declaration//GEN-END:variables
}
