/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SubPanel_View.java
 *
 * Created on Mar 14, 2012, 2:29:23 PM
 */
package travelsmart;

/**
 *
 * @author Mero
 */
public class SubPanel_View extends javax.swing.JPanel {

    /** Creates new form SubPanel_View */
    public SubPanel_View() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        bttSaveMap = new javax.swing.JButton();
        bttEditPoint = new javax.swing.JButton();
        bttEditLine = new javax.swing.JButton();

        setName("Form"); // NOI18N
        setOpaque(false);
        setLayout(new java.awt.GridBagLayout());

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(travelsmart.TravelSmart.class).getContext().getResourceMap(SubPanel_View.class);
        bttSaveMap.setIcon(resourceMap.getIcon("bttSaveMap.icon")); // NOI18N
        bttSaveMap.setBorder(null);
        bttSaveMap.setContentAreaFilled(false);
        bttSaveMap.setFocusPainted(false);
        bttSaveMap.setMargin(new java.awt.Insets(0, 0, 0, 0));
        bttSaveMap.setName("bttSaveMap"); // NOI18N
        bttSaveMap.setPressedIcon(resourceMap.getIcon("bttSaveMap.pressedIcon")); // NOI18N
        bttSaveMap.setRolloverIcon(resourceMap.getIcon("bttSaveMap.rolloverIcon")); // NOI18N
        bttSaveMap.setRolloverSelectedIcon(resourceMap.getIcon("bttSaveMap.rolloverSelectedIcon")); // NOI18N
        bttSaveMap.setSelected(true);
        bttSaveMap.setSelectedIcon(resourceMap.getIcon("bttSaveMap.selectedIcon")); // NOI18N
        bttSaveMap.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                bttSaveMapMouseMoved(evt);
            }
        });
        bttSaveMap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttSaveMapActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        add(bttSaveMap, gridBagConstraints);

        bttEditPoint.setIcon(resourceMap.getIcon("bttEditPoint.icon")); // NOI18N
        bttEditPoint.setBorder(null);
        bttEditPoint.setContentAreaFilled(false);
        bttEditPoint.setFocusPainted(false);
        bttEditPoint.setMargin(new java.awt.Insets(0, 0, 0, 0));
        bttEditPoint.setName("bttEditPoint"); // NOI18N
        bttEditPoint.setPressedIcon(resourceMap.getIcon("bttEditPoint.pressedIcon")); // NOI18N
        bttEditPoint.setRolloverIcon(resourceMap.getIcon("bttEditPoint.rolloverIcon")); // NOI18N
        bttEditPoint.setRolloverSelectedIcon(resourceMap.getIcon("bttEditPoint.rolloverSelectedIcon")); // NOI18N
        bttEditPoint.setSelectedIcon(resourceMap.getIcon("bttEditPoint.selectedIcon")); // NOI18N
        bttEditPoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttEditPointActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        add(bttEditPoint, gridBagConstraints);

        bttEditLine.setIcon(resourceMap.getIcon("bttEditLine.icon")); // NOI18N
        bttEditLine.setBorder(null);
        bttEditLine.setContentAreaFilled(false);
        bttEditLine.setFocusPainted(false);
        bttEditLine.setMargin(new java.awt.Insets(0, 0, 0, 0));
        bttEditLine.setMinimumSize(new java.awt.Dimension(0, 0));
        bttEditLine.setName("bttEditLine"); // NOI18N
        bttEditLine.setPressedIcon(resourceMap.getIcon("bttEditLine.pressedIcon")); // NOI18N
        bttEditLine.setRolloverIcon(resourceMap.getIcon("bttEditLine.rolloverIcon")); // NOI18N
        bttEditLine.setRolloverSelectedIcon(resourceMap.getIcon("bttEditLine.rolloverSelectedIcon")); // NOI18N
        bttEditLine.setSelectedIcon(resourceMap.getIcon("bttEditLine.selectedIcon")); // NOI18N
        bttEditLine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttEditLineActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        add(bttEditLine, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

private void bttSaveMapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttSaveMapActionPerformed
    bttSaveMap.setSelected(true);
    bttEditLine.setSelected(false);
    bttEditPoint.setSelected(false);
    TravelSmart.getView().pn_Map.ChangeMapOption(MapStatus.VIEW);
}//GEN-LAST:event_bttSaveMapActionPerformed

private void bttEditLineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttEditLineActionPerformed
    bttSaveMap.setSelected(false);
    bttEditLine.setSelected(true);
    bttEditPoint.setSelected(false);   
    TravelSmart.getView().pn_Map.ChangeMapOption(MapStatus.EDIT_LINE);
}//GEN-LAST:event_bttEditLineActionPerformed

private void bttEditPointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttEditPointActionPerformed
    bttSaveMap.setSelected(false);
    bttEditLine.setSelected(false);
    bttEditPoint.setSelected(true);  
    TravelSmart.getView().pn_Map.ChangeMapOption(MapStatus.EDIT_POINT);
}//GEN-LAST:event_bttEditPointActionPerformed

private void bttSaveMapMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bttSaveMapMouseMoved

}//GEN-LAST:event_bttSaveMapMouseMoved

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttEditLine;
    private javax.swing.JButton bttEditPoint;
    private javax.swing.JButton bttSaveMap;
    // End of variables declaration//GEN-END:variables
}
