/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SubPanel_Search.java
 *
 * Created on Mar 10, 2012, 12:15:39 PM
 */
package travelsmart;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.event.KeyEvent;
import javax.swing.ImageIcon;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 *
 * @author dato
 */
public class SubPanel_Search extends javax.swing.JPanel {

    String bg=Config.SearchP_bg_normal;
    
    /** Creates new form SubPanel_Search */
    public SubPanel_Search() {
        this.setOpaque(false);
        this.setSize(TravelSmart.GetScreenSize().width - 100, 30);
        initComponents();
        this.txtSearch.getDocument().addDocumentListener(new DocumentListener() {
            public void changedUpdate(DocumentEvent e) {
                warn();
            }
            public void removeUpdate(DocumentEvent e) {
                warn();
            }
            public void insertUpdate(DocumentEvent e) {
                warn();
            }

            public void warn() {                
                TravelSmart.getView().dgl_searchresult.SearchName(txtSearch.getText());
            }
        });
    }
    
    @Override
    public void paintComponent(Graphics g){
        Graphics2D g2 = (Graphics2D)g;
        if(!bg.equals("")){        
            g2.drawImage(new ImageIcon(bg).getImage(), 0,0,this.getWidth(),this.getHeight(), null);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        txtSearch = new javax.swing.JTextField();
        bttSearch = new javax.swing.JButton();

        setName("Form"); // NOI18N
        setOpaque(false);
        setLayout(new java.awt.GridBagLayout());

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(travelsmart.TravelSmart.class).getContext().getResourceMap(SubPanel_Search.class);
        txtSearch.setFont(resourceMap.getFont("txtSearch.font")); // NOI18N
        txtSearch.setForeground(resourceMap.getColor("txtSearch.foreground")); // NOI18N
        txtSearch.setText(resourceMap.getString("txtSearch.text")); // NOI18N
        txtSearch.setBorder(null);
        txtSearch.setName("txtSearch"); // NOI18N
        txtSearch.setOpaque(false);
        txtSearch.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSearchFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSearchFocusLost(evt);
            }
        });
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSearchKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 400;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        add(txtSearch, gridBagConstraints);

        bttSearch.setBackground(resourceMap.getColor("bttSearch.background")); // NOI18N
        bttSearch.setIcon(resourceMap.getIcon("bttSearch.icon")); // NOI18N
        bttSearch.setText(resourceMap.getString("bttSearch.text")); // NOI18N
        bttSearch.setBorder(null);
        bttSearch.setContentAreaFilled(false);
        bttSearch.setFocusPainted(false);
        bttSearch.setMargin(new java.awt.Insets(0, 0, 0, 0));
        bttSearch.setName("bttSearch"); // NOI18N
        bttSearch.setPressedIcon(resourceMap.getIcon("bttSearch.pressedIcon")); // NOI18N
        bttSearch.setRolloverIcon(resourceMap.getIcon("bttSearch.rolloverIcon")); // NOI18N
        bttSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttSearchActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        add(bttSearch, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

private void txtSearchFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSearchFocusGained
    if(txtSearch.getText().equals("Type name in here")){
        txtSearch.setText("");
    }
    bg=Config.SearchP_bg_focus;
    repaint();
}//GEN-LAST:event_txtSearchFocusGained

private void txtSearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyPressed

    switch(evt.getKeyCode()){
        case KeyEvent.VK_ENTER:
            TravelSmart.getView().pn_Map.SearchPoint(txtSearch.getText(),0);
            if(TravelSmart.getView().dgl_searchresult.isVisible()){
                TravelSmart.getView().dgl_searchresult.setVisible(false);
            }
            break;
        case KeyEvent.VK_ESCAPE:
            if(TravelSmart.getView().dgl_searchresult.isVisible()){
                TravelSmart.getView().dgl_searchresult.setVisible(false);
            }
            break;
        case KeyEvent.VK_UP:
            TravelSmart.getView().dgl_searchresult.ShowDgl(txtSearch);
            TravelSmart.getView().dgl_searchresult.NextItem();
            break;
        case KeyEvent.VK_LEFT:
            TravelSmart.getView().dgl_searchresult.ShowDgl(txtSearch);
            TravelSmart.getView().dgl_searchresult.NextItem();
            break;
        case KeyEvent.VK_DOWN:
            TravelSmart.getView().dgl_searchresult.ShowDgl(txtSearch);
            TravelSmart.getView().dgl_searchresult.NextItem();
            break;
        case KeyEvent.VK_RIGHT:
            TravelSmart.getView().dgl_searchresult.ShowDgl(txtSearch);
            TravelSmart.getView().dgl_searchresult.NextItem();
            break; 
        default:    TravelSmart.getView().dgl_searchresult.ShowDgl(txtSearch);
    }
}//GEN-LAST:event_txtSearchKeyPressed

private void bttSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttSearchActionPerformed
    TravelSmart.getView().pn_Map.SearchPoint(txtSearch.getText(),0);
    TravelSmart.getView().dgl_searchresult.setVisible(false);
}//GEN-LAST:event_bttSearchActionPerformed

private void txtSearchFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSearchFocusLost
    bg=Config.SearchP_bg_normal;
    repaint();
}//GEN-LAST:event_txtSearchFocusLost

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttSearch;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables

}
