/*
 * TravelSmartView.java
 */

package travelsmart;

import org.jdesktop.application.Action;
import org.jdesktop.application.SingleFrameApplication;
import org.jdesktop.application.FrameView;
import javax.swing.JDialog;
import javax.swing.JFrame;

/**
 * The application's main frame.
 */
public class TravelSmartView extends FrameView {
    dgl_AddPoint dgl_addPoint = new dgl_AddPoint();
    dgl_EditPoint dgl_editPoint = new dgl_EditPoint();
    dgl_EditLine dgl_editLine = new dgl_EditLine();
    dgl_AddLine dgl_addLine = new dgl_AddLine();
    dgl_SearchResult dgl_searchresult = new dgl_SearchResult();

    public TravelSmartView(SingleFrameApplication app) {
        super(app);
        this.getFrame().setExtendedState(JFrame.MAXIMIZED_BOTH);
        
        initComponents();
        this.mainPanel1.bgUrl = Config.Main_Background;
    }

    @Action
    public void showAboutBox() {
        if (aboutBox == null) {
            JFrame mainFrame = TravelSmart.getApplication().getMainFrame();
            aboutBox = new TravelSmartAboutBox(mainFrame);
            aboutBox.setLocationRelativeTo(mainFrame);
        }
        TravelSmart.getApplication().show(aboutBox);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        mainPanel = new javax.swing.JPanel();
        mainPanel1 = new travelsmart.bgPanel();
        searchPointPanel1 = new travelsmart.SubPanel_Search();
        pn_Map = new travelsmart.SubPanel_Map();
        searchDirectionPanel1 = new travelsmart.SubPanel_Route();
        subPanel_View1 = new travelsmart.SubPanel_View();

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(travelsmart.TravelSmart.class).getContext().getResourceMap(TravelSmartView.class);
        mainPanel.setBackground(resourceMap.getColor("mainPanel.background")); // NOI18N
        mainPanel.setName("mainPanel"); // NOI18N
        mainPanel.setLayout(new javax.swing.BoxLayout(mainPanel, javax.swing.BoxLayout.LINE_AXIS));

        mainPanel1.setName("mainPanel1"); // NOI18N
        mainPanel1.setLayout(new java.awt.GridBagLayout());

        searchPointPanel1.setName("searchPointPanel1"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(15, 15, 10, 0);
        mainPanel1.add(searchPointPanel1, gridBagConstraints);

        pn_Map.setBackground(resourceMap.getColor("pn_Map.background")); // NOI18N
        pn_Map.setName("pn_Map"); // NOI18N
        pn_Map.setPreferredSize(new java.awt.Dimension(815, 300));

        javax.swing.GroupLayout pn_MapLayout = new javax.swing.GroupLayout(pn_Map);
        pn_Map.setLayout(pn_MapLayout);
        pn_MapLayout.setHorizontalGroup(
            pn_MapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1142, Short.MAX_VALUE)
        );
        pn_MapLayout.setVerticalGroup(
            pn_MapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 407, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 15, 0, 15);
        mainPanel1.add(pn_Map, gridBagConstraints);

        searchDirectionPanel1.setBackground(resourceMap.getColor("searchDirectionPanel1.background")); // NOI18N
        searchDirectionPanel1.setMaximumSize(new java.awt.Dimension(32767, 32767));
        searchDirectionPanel1.setMinimumSize(new java.awt.Dimension(0, 0));
        searchDirectionPanel1.setName("searchDirectionPanel1"); // NOI18N
        searchDirectionPanel1.setPreferredSize(new java.awt.Dimension(758, 73));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LAST_LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 15, 15, 15);
        mainPanel1.add(searchDirectionPanel1, gridBagConstraints);

        subPanel_View1.setMinimumSize(new java.awt.Dimension(300, 0));
        subPanel_View1.setName("subPanel_View1"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(15, 0, 10, 15);
        mainPanel1.add(subPanel_View1, gridBagConstraints);

        mainPanel.add(mainPanel1);

        setComponent(mainPanel);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel mainPanel;
    private travelsmart.bgPanel mainPanel1;
    public travelsmart.SubPanel_Map pn_Map;
    public travelsmart.SubPanel_Route searchDirectionPanel1;
    public travelsmart.SubPanel_Search searchPointPanel1;
    private travelsmart.SubPanel_View subPanel_View1;
    // End of variables declaration//GEN-END:variables


    private JDialog aboutBox;
}
